# Generated by Django 5.0.2 on 2024-03-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_panel', '0002_treatmentplan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentplan',
            old_name='user',
            new_name='therapist',
        ),
    ]
