# Generated by Django 5.0.2 on 2024-03-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_panel', '0005_alter_treatmentplan_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='therapist',
        ),
    ]
