# Generated by Django 5.0.2 on 2024-03-21 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionnaire',
            name='question_five',
            field=models.TextField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Occasionally', 'Occasionally'), ('Frequently', 'Frequently'), ('Always', 'Always')], verbose_name='Have you ever had difficulty understanding or following conversations?'),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='question_four',
            field=models.TextField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Occasionally', 'Occasionally'), ('Frequently', 'Frequently'), ('Always', 'Always')], verbose_name='Do you struggle with stuttering or stammering?'),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='question_one',
            field=models.TextField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Occasionally', 'Occasionally'), ('Frequently', 'Frequently'), ('Always', 'Always')], verbose_name='How often do you experience difficulty pronouncing certain sounds?'),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='question_three',
            field=models.TextField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Occasionally', 'Occasionally'), ('Frequently', 'Frequently'), ('Always', 'Always')], verbose_name='Have you noticed any changes in your voice quality or pitch recently?'),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='question_two',
            field=models.TextField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Occasionally', 'Occasionally'), ('Frequently', 'Frequently'), ('Always', 'Always')], verbose_name='Do you feel confident when speaking in public?'),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
