# Generated by Django 5.0.2 on 2024-03-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_userquestionnaire_question_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='name',
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='comments',
            field=models.CharField(default=1, max_length=30, verbose_name='Additional Comments/Feedback:'),
            preserve_default=False,
        ),
    ]
