# Generated by Django 5.0.2 on 2024-03-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_userquestionnaire_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionnaire',
            name='comments',
            field=models.CharField(max_length=500, verbose_name='Additional Comments/Feedback:'),
        ),
    ]
