# Generated by Django 5.0.2 on 2024-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_userquestionnaire_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionnaire',
            name='question_one',
            field=models.TextField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Occasionally', 'Occasionally'), ('Frequently', 'Frequently'), ('Always', 'Always')], help_text='AlaBala', verbose_name='How often do you experience difficulty pronouncing certain sounds?'),
        ),
    ]
