# Generated by Django 5.0.2 on 2024-03-25 10:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_userquestionnaire_question_one'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionnaire',
            name='question_one',
            field=models.TextField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Occasionally', 'Occasionally'), ('Frequently', 'Frequently'), ('Always', 'Always')], verbose_name='How often do you experience difficulty pronouncing certain sounds?'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Pediatric speech service', 'Pediatric speech service'), ('Adult speech service', 'Adult speech service'), ('Occupational therapy service', 'Occupational therapy service')], default='Pediatric speech service', max_length=50)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('3 PM', '3 PM'), ('4 PM', '4 PM'), ('5 PM', '5 PM'), ('6 PM', '6 PM'), ('7 PM', '7 PM')], default='3 PM', max_length=10)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
