# Generated by Django 5.0.2 on 2024-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_userquestionnaire_question_one_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionnaire',
            name='comments',
            field=models.TextField(max_length=500, verbose_name='Additional Comments/Feedback:'),
        ),
    ]
