# Generated by Django 5.0.2 on 2024-03-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_speachcenteruser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speachcenteruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='speachcenteruser',
            name='last_name',
        ),
    ]
