# Generated by Django 5.0.2 on 2024-03-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='previous_speech_therapy_history',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
    ]
