# Generated by Django 5.0.2 on 2024-03-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_previous_speech_therapy_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reasons_for_therapy',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
