# Generated by Django 5.0.2 on 2024-03-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reasons_for_therapy',
            field=models.TextField(blank=True, choices=[('cognitive (intellectual, thinking) developmental delays', 'cognitive (intellectual, thinking) developmental delays'), ('weak oral muscles', 'weak oral muscles'), ('cleft lip or palate', 'cleft lip or palate'), ('autism', 'autism'), ('motor planning problems', 'motor planning problems'), ('articulation problems', 'articulation problems'), ('other', 'other')], null=True),
        ),
    ]
