# Generated by Django 5.0.2 on 2024-03-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_reasons_for_therapy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='previous_speech_therapy_history',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
    ]
